name: Webhook Trigger

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Flask server
        run: |
          echo "Starting webhook test"
          curl -v -X POST https://1c20-2409-40e3-3056-9a89-fd68-4272-e963-f1ae.ngrok-free.app/webhook \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: ${{ github.event_name }}" \
          -d '${{ toJson(github) }}'
